{{- if .Values.persistence.elasticsearch.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reportportal-elasticsearch
  labels: {{ include "labels" . | indent 4 }}
spec:
  claimRef:
    namespace: default
    name: reportportal-elasticsearch
{{ toYaml .Values.persistence.elasticsearch.spec | indent 2 }}
{{- end -}}