{{- if .Values.persistence.mongodb.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reportportal-mongodb
  labels: {{ include "labels" . | indent 4 }}
spec:
  claimRef:
    namespace: default
    name: reportportal-mongodb
{{ toYaml .Values.persistence.mongodb.spec | indent 2 }}
{{- end -}}