{{- if .Values.persistence.registry.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reportportal-registry
  labels: {{ include "labels" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.registry.spec.capacity.storage }}
  volumeName: reportportal-registry
{{- end -}}