{{- if .Values.persistence.registry.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reportportal-registry
  labels: {{ include "labels" . | indent 4 }}
spec:
  claimRef:
    namespace: default
    name: reportportal-registry
{{ toYaml .Values.persistence.registry.spec | indent 2 }}
{{- end -}}